# Generated by Django 5.1 on 2024-08-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_apis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
