# Generated by Django 5.1 on 2024-08-19 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_apis', '0002_remove_user_id_user_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
    ]
