# Generated by Django 5.1 on 2024-08-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('position', models.CharField(default='', max_length=255)),
                ('department', models.CharField(default='', max_length=255)),
                ('phone', models.CharField(default='', max_length=255)),
                ('email', models.CharField(default='', max_length=255)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reviewer_id', models.IntegerField(default=0, max_length=255)),
                ('employee_id', models.IntegerField(default=0, max_length=255)),
                ('review', models.TextField(default='', max_length=255)),
            ],
        ),
    ]
